In [1]:
datos = ['A','1','2','B','3','4']

In [4]:
lista_a = datos[0:3]
lista_a

['A', '1', '2']

In [13]:
lista_b = datos[3:6]
lista_b

['B', '3', '4']

In [16]:
datos=['A','1','2','B','3','4','A','1','2','B','3','4','A','1','2','B','3','4']
datos

['A',
 '1',
 '2',
 'B',
 '3',
 '4',
 'A',
 '1',
 '2',
 'B',
 '3',
 '4',
 'A',
 '1',
 '2',
 'B',
 '3',
 '4']

In [23]:
datos_tupla = tuple(datos)
datos_tupla.count('A'), datos_tupla.count('B'), datos_tupla.count('1')

(3, 3, 3)

## Liberias

In [3]:
import numpy

In [4]:
numpy.random.randint(10)

0

In [46]:
import awswrangler

ModuleNotFoundError: ignored

In [47]:
! pip install awswrangler

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 251 kB 28.5 MB/s 
     |████████████████████████████████| 43 kB 2.3 MB/s 
     |████████████████████████████████| 112 kB 60.7 MB/s 
     |████████████████████████████████| 132 kB 63.4 MB/s 
     |████████████████████████████████| 73 kB 1.8 MB/s 
     |████████████████████████████████| 204 kB 74.7 MB/s 
     |████████████████████████████████| 9.2 MB 44.4 MB/s 
     |████████████████████████████████| 79 kB 8.8 MB/s 
     |████████████████████████████████| 140 kB 50.3 MB/s 
     |████████████████████████████████| 41 kB 603 kB/s 
     |████████████████████████████████| 1.1 MB 48.4 MB/s 
     |████████████████████████████████| 131 kB 70.9 MB/s 
     |████████████████████████████████| 49 kB 5.9 MB/s 
     |████████████████████████████████| 128 kB 52.1 MB/s 
     |████████████████████████████████| 127 kB 53.9 MB/s 
     |████████████████████████████████| 1

In [6]:
import awswrangler as wr

In [5]:
! pip freeze # Listar las librerias que tenemos instaladas

absl-py==1.2.0
aenum==3.1.11
aeppl==0.0.33
aesara==2.7.9
aiohttp==3.8.1
aiosignal==1.2.0
alabaster==0.7.12
albumentations==1.2.1
altair==4.2.0
appdirs==1.4.4
arviz==0.12.1
asn1crypto==1.5.1
astor==0.8.1
astropy==4.3.1
astunparse==1.6.3
async-timeout==4.0.2
asynctest==0.13.0
atari-py==0.2.9
atomicwrites==1.4.1
attrs==22.1.0
audioread==3.0.0
autograd==1.5
awswrangler==2.17.0
Babel==2.10.3
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.11.1
bleach==5.0.1
blis==0.7.8
bokeh==2.3.3
boto3==1.24.91
botocore==1.27.91
branca==0.5.0
bs4==0.0.1
CacheControl==0.12.11
cached-property==1.5.2
cachetools==4.2.4
catalogue==2.0.8
certifi==2022.9.24
cffi==1.15.1
cftime==1.6.2
chardet==3.0.4
charset-normalizer==2.1.1
click==7.1.2
clikit==0.6.2
cloudpickle==1.5.0
cmake==3.22.6
cmdstanpy==1.0.7
colorcet==3.0.1
colorlover==0.3.0
community==1.0.0b1
confection==0.0.3
cons==0.4.5
contextlib2==0.5.5
convertdate==2.4.0
crashtest==0.3.1
crcmod==1.7
cufflinks==0.17.3
cvxopt==1.3.0
cvxpy==1.2.1
cycler==0.11.0
cymem

In [7]:
import numpy as np

In [31]:
np.random.randint(1, 100)

17

In [32]:
import math

In [34]:
2 * math.pi 

6.283185307179586

In [40]:
math.degrees(0.45)

25.783100780887047

In [44]:
math.floor(4.99999999999999) # Redondear numeros hacia abajo siempre

4

In [46]:
math.ceil(4.111111111111) # Redondear numeros hacia arriba siempre

5

In [49]:
import numpy as np

In [ ]:
zeros = [0, 0, 0, 0, ....]
zeros = []

for i in range(100):
  zeros.append(i)

In [54]:
np.zeros(100)[0:5]

array([0., 0., 0., 0., 0.])

In [70]:
np.random.rand(0, 10, 100)

array([], shape=(0, 10, 100), dtype=float64)

In [67]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.random.rand(30)

array([0.9893312 , 0.37639513, 0.85252138, 0.56952108, 0.25753376,
       0.36270214, 0.73751131, 0.16668254, 0.43376649, 0.62988259,
       0.4417638 , 0.19595751, 0.54809262, 0.9890106 , 0.64077851,
       0.25330724, 0.30944001, 0.2394818 , 0.71303963, 0.06125745,
       0.87358324, 0.29508349, 0.39041956, 0.55734615, 0.37765148,
       0.32220185, 0.09744869, 0.12555405, 0.96381255, 0.22690817])

In [92]:
np.random.randint(100, 999)

329

In [93]:
cadena = 'este esto es minuscula'
cadena

'este esto es minuscula'

In [95]:
cadena.upper()

'ESTE ESTO ES MINUSCULA'

In [97]:
cadena.lower()

'este esto es minuscula'

In [99]:
vocales = 'aeiou'
cadena  = cadena.lower()

In [102]:
personas = {
    1 : {
        'nombre'    : 'Yorman',
        'edad'      : 28,
        'nro_hijos' : 0
    },
    2 : {
        'nombre'    : 'Pepito',
        'edad'      : 15,
        'nro_hijos' : 0
    },
    3 : {
        'nombre'    : 'Carolina',
        'edad'      : 33,
        'nro_hijos' : 5
    },
    4 : {
        'nombre'    : 'Carlitos',
        'edad'      : 11,
        'nro_hijos' : 0
    },
    5 : {
        'nombre'    : 'Fulanita',
        'edad'      : 35,
        'nro_hijos' : 2
    },
}

In [104]:
# 1. Identificar la cantidad de personas en la lista
# 2. Cantidad de personas con edad mayor o igual que 15
# 3. Cantidad de personas con hijos
# 4. Suma total de hijos de las personas
# 5. Número unico de cantidad de hijos 

In [134]:
nro_personas           = len(personas)
nro_peronas_mayor15    = 0
cnt_personas_con_hijos = 0
suma_total_hijos       = 0
lista_nro_hijos        = [] # Inicializamos la lista vacia para irla llenando con los numeros de hijos de cada persona
nro_unico_cnt_hijos    = 0

for key, persona in personas.items():
  if persona['edad'] >= 15:
    nro_peronas_mayor15 += 1

  if persona['nro_hijos'] > 0:
    cnt_personas_con_hijos += 1
    suma_total_hijos += persona['nro_hijos']
  
  lista_nro_hijos.append(persona['nro_hijos'])


lista_nro_hijos = set(lista_nro_hijos)
nro_unico_cnt_hijos = len(lista_nro_hijos)


print(f"1. número de personas: {nro_personas}")
print(f"2. Cantidad de personas con edad mayor o igual que 15: {nro_peronas_mayor15}")
print(f"3. Cantidad de personas con hijos: {cnt_personas_con_hijos}")
print(f"4. Suma total de hijos de las personas: {suma_total_hijos}")
print(f"5. Número unico de cantidad de hijos: {nro_unico_cnt_hijos}")

1. número de personas: 5
2. Cantidad de personas con edad mayor o igual que 15: 4
3. Cantidad de personas con hijos: 2
4. Suma total de hijos de las personas: 7
5. Número unico de cantidad de hijos: 3
