In [1]:
! pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy as np

In [4]:
lista_numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
len(lista_numeros)

9

In [7]:
lista_numeros[1:5]

[2, 3, 4, 5]

In [8]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(array1)

numpy.ndarray

In [10]:
lista_numeros.sum()

AttributeError: ignored

In [11]:
array1.sum()

45

In [12]:
array1.mean()

5.0

In [14]:
array1.std()

2.581988897471611

In [16]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array1.ndim

1

In [17]:
array1.shape

(9,)

In [22]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
array2.ndim

2

In [24]:
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
array2[1][2]

6

In [27]:
array2[0]

array([1, 2, 3])

In [28]:
array2.sum()

45

In [29]:
array2.shape

(3, 3)

In [33]:
array3 = np.array([[1, 2, 3],[4, 5], [6, 7, 8, 9], [10, 11]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [34]:
print(array3)

[list([1, 2, 3]) list([4, 5]) list([6, 7, 8, 9]) list([10, 11])]


In [35]:
array3.shape

(4,)

In [38]:
array3.sum()

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [40]:
array4 = np.array([[1, 2],[3, 4],[50, 52]])

In [41]:
print(array4)

[[ 1  2]
 [ 3  4]
 [50 52]]


In [42]:
array4.sum()

112

In [43]:
array4.ndim

2

In [44]:
array4.shape

(3, 2)

In [45]:
array4.size

6

In [47]:
array4

array([[ 1,  2],
       [ 3,  4],
       [50, 52]])

In [51]:
array_nuevo = np.append(array4, [66, 67])

In [52]:
print(array_nuevo)

[ 1  2  3  4 50 52 66 67]


In [54]:
array_nuevo.sum()

245

In [53]:
array_nuevo.ndim

1

In [55]:
array4

array([[ 1,  2],
       [ 3,  4],
       [50, 52]])

In [64]:
np.insert(array4, 2, [77, 78], axis = 0) # Axis = 0, se utiliza para hacer uniones en las filas

array([[ 1,  2],
       [ 3,  4],
       [77, 78],
       [50, 52]])

In [70]:
np.insert(array4, 2, [77, 78, 79], axis = 1) # Axis = 1, se utiliza para hacer uniones en las columnas

array([[ 1,  2, 77],
       [ 3,  4, 78],
       [50, 52, 79]])

In [71]:
np.zeros((5, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
np.ones((5, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [73]:
new_array = np.insert(array4, 2, [77, 78, 79], axis = 1) # Axis = 1, se utiliza para hacer uniones en las columnas

In [74]:
new_array

array([[ 1,  2, 77],
       [ 3,  4, 78],
       [50, 52, 79]])

In [75]:
new_array.sum()

346

In [77]:
new_array.sum(axis = 1)

array([ 80,  85, 181])

In [78]:
new_array.sum(axis = 0)

array([ 54,  58, 234])

In [82]:
new_array.sum(axis = (1))

array([ 80,  85, 181])

In [83]:
np.sum([[0, 1], [0, 5]], axis=0)

array([0, 6])

In [84]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])

In [85]:
x = np.arange(12).reshape((3,4))

In [86]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
x.sum(axis = 1)

array([ 6, 22, 38])

In [88]:
x.sum(axis = 0)

array([12, 15, 18, 21])

In [95]:
import pandas as pd



In [98]:
df = pd.DataFrame({'col1': [0, 4, 8], 'col2' : [1, 5, 9], 'col3' : [2, 6, 10], 'col4' : [3, 7, 11]})
df

col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11

In [101]:
df.sum(axis = 1)

0     6
1    22
2    38
dtype: int64

In [107]:
pd.concat([df, pd.DataFrame([95, 96, 97])], axis = 1, ignore_index = True)

0  1   2   3   4
0  0  1   2   3  95
1  4  5   6   7  96
2  8  9  10  11  97

In [113]:
pd.concat([df, pd.DataFrame({'col4' : [95]})], axis = 0, ignore_index = True)

col1  col2  col3  col4
0   0.0   1.0   2.0     3
1   4.0   5.0   6.0     7
2   8.0   9.0  10.0    11
3   NaN   NaN   NaN    95

In [114]:
array10 = np.insert(array4, 2, [77, 78], axis = 0)

In [115]:
array10

array([[ 1,  2],
       [ 3,  4],
       [77, 78],
       [50, 52]])

In [116]:
array10.sum()

267

In [117]:
array10.sum(axis = 0)

array([131, 136])

In [118]:
array10.sum(axis = 1)

array([  3,   7, 155, 102])

## Aclaración de como usar el Axis = 0 y el Axis = 1

* Axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).


https://docs.scipy.org/doc/numpy-1.10.0/glossary.html#:~:text=Axes%20are%20defined%20for%20arrays,across%20columns%20(axis%201).

In [119]:
array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
# array[fila_inicial : fila_final , col_inicial : col_final]
#  :  significa sacar TODO

In [134]:
array[0:3, 1:3]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [128]:
array[0:3, 1:3].sum()

27

In [133]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
array[0:2, : ]

array([[0, 1, 2],
       [3, 4, 5]])

### Reto 1

In [141]:
frutas          = ['Banano','Mango','Banano','Papaya','Mango','Corozo','Mango','Mango','Pera']
frutas_deseadas = ['Mango','Corozo']
frutas

['Banano',
 'Mango',
 'Banano',
 'Papaya',
 'Mango',
 'Corozo',
 'Mango',
 'Mango',
 'Pera']

In [143]:
cont_bananos  = 0
cont_mango    = 0
cont_deseadas = 0

for fruta in frutas:
  if fruta == 'Banano':
    cont_bananos += 1
  elif fruta == 'Mango':
    cont_mango += 1

  if fruta in frutas_deseadas:
    cont_deseadas += 1

print(cont_bananos)
print(cont_mango)
print(cont_deseadas)

2
4
5


In [147]:
cadena = 'Ese Perro es de color amarillo'
vocales = 'aeiou'

for letra in cadena:
  if letra in vocales:
    print(f'{letra} es una vocal!')

e es una vocal!
e es una vocal!
o es una vocal!
e es una vocal!
e es una vocal!
o es una vocal!
o es una vocal!
a es una vocal!
a es una vocal!
i es una vocal!
o es una vocal!


In [148]:
lista_ventas = ['mantequilla', '4', 'mantequilla', '5', 'carne', '1', 'huevos', '5', 'carne', '2', 'carne', '1',
'huevos', '1', 'grano', '1', 'carne', '5', 'grano', '5', 'pan', '3', 'mantequilla', '5', 'huevos', '3']

In [150]:
productos = {
    'leche'       : 0,
    'huevos'      : 0,
    'mantequilla' : 0
}

In [179]:
list(productos.values())

[0, 0, 0]

In [166]:
productos['mantequilla']

0

In [157]:
cnt_grupos_ventas = len(lista_ventas) / 2

In [162]:
array_ventas = np.array_split(lista_ventas, cnt_grupos_ventas)
array_ventas

[array(['mantequilla', '4'], dtype='<U11'),
 array(['mantequilla', '5'], dtype='<U11'),
 array(['carne', '1'], dtype='<U11'),
 array(['huevos', '5'], dtype='<U11'),
 array(['carne', '2'], dtype='<U11'),
 array(['carne', '1'], dtype='<U11'),
 array(['huevos', '1'], dtype='<U11'),
 array(['grano', '1'], dtype='<U11'),
 array(['carne', '5'], dtype='<U11'),
 array(['grano', '5'], dtype='<U11'),
 array(['pan', '3'], dtype='<U11'),
 array(['mantequilla', '5'], dtype='<U11'),
 array(['huevos', '3'], dtype='<U11')]

In [175]:
mantequilla = 0
leche       = 0
huevos      = 0

for prod in array_ventas:
  if prod[0] == 'mantequilla':
    mantequilla += int(prod[1])
  elif prod[0] == 'leche':
    leche += int(prod[1])
  elif prod[0] == 'huevos':
    huevos += int(prod[1])

In [171]:
mantequilla

14

In [172]:
leche

0

In [174]:
huevos

9

In [182]:
len(lista_ventas)

26

In [186]:
for i in range(len(lista_ventas)):
  if i % 2 == 0:
    print(lista_ventas[i], lista_ventas[i+1])

mantequilla 4
mantequilla 5
carne 1
huevos 5
carne 2
carne 1
huevos 1
grano 1
carne 5
grano 5
pan 3
mantequilla 5
huevos 3
